WADProject/Controllers/MenuItemController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using WADProject.Models;
using WADProject.Repositories;
using WADProject.Services;

namespace WADProject.Controllers
{
    public class MenuItemController : Controller
    {
        private readonly MenuItemService _menuItemService;
        private readonly IUnitOfWork _unitOfWork;

        public MenuItemController(MenuItemService menuItemService, IUnitOfWork unitOfWork)
        {
            _menuItemService = menuItemService;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            var menuItems = _menuItemService.GetMenuItems();
            return View(menuItems);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menuItem = _menuItemService.GetMenuItems().FirstOrDefault(m => m.MenuItemId == id);
            if (menuItem == null)
            {
                return NotFound();
            }

            return View(menuItem);
        }

        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Administrator")]
        public IActionResult Index2()
        {
            var menuItems = _menuItemService.GetMenuItems();
            return View(menuItems);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("MenuItemId, Description, Name, Picture, Price")] MenuItem menuItem)
        {
            if (ModelState.IsValid)
            {
                _menuItemService.AddMenuItem(menuItem);
                _menuItemService.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(menuItem);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservations = _menuItemService.GetMenuItems().FirstOrDefault(m => m.MenuItemId== id);
            if (reservations == null)
            {
                return NotFound();
            }
            return View(reservations);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(int id, [Bind("MenuItemId, Description, Name,")] MenuItem menuItem)
        {
            if (id != menuItem.MenuItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _menuItemService.UpdateMenuItem(menuItem);
                    _menuItemService.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(menuItem.MenuItemId))
                    {
                        return NotFound();
                    }

                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(menuItem);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menuItem = _menuItemService.GetMenuItems().FirstOrDefault(m => m.MenuItemId == id);
            if (menuItem == null)
            {
                return NotFound();
            }

            return View(menuItem);
        }

        [Authorize(Roles = "Administrator")]

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var menuItem = _menuItemService.GetMenuItems().FirstOrDefault();
            _menuItemService.DeleteMenuItem(menuItem);
            _menuItemService.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _menuItemService.GetMenuItems().Any(e => e.MenuItemId== id);
        }
    }
}

WADProject/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WADProject.Models;
using WADProject.Services;

namespace WADProject.Controllers
{
    public class ReservationController : Controller
    {
        private readonly ReservationService _reservationService;

        public ReservationController(ReservationService reservationService)
        {
            _reservationService = reservationService;
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Index()
        {
            var reservations = _reservationService.GetReservations();
            return View(reservations);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservations = _reservationService.GetReservations().FirstOrDefault(m => m.ReservationId == id);
            if (reservations == null)
            {
                return NotFound();
            }

            return View(reservations);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("ReservationId,Name,NumberOfPersons,DateApplied,DateOfSchedule")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                _reservationService.AddReservation(reservation);
                _reservationService.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(reservation);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservations = _reservationService.GetReservations().FirstOrDefault(m => m.ReservationId == id);
            if (reservations == null)
            {
                return NotFound();
            }
            return View(reservations);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("ReservationId, Name, NumberOfPersons, DateApplied, DateOfSchedule")] Reservation reservation)
        {
            if (id != reservation.ReservationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _reservationService.UpdateReservation(reservation);
                    _reservationService.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(reservation.ReservationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reservation);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = _reservationService.GetReservations().FirstOrDefault(m => m.ReservationId == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var reservation = _reservationService.GetReservationsByCondition(b => b.ReservationId == id).FirstOrDefault();
            _reservationService.DeleteReservation(reservation);
            _reservationService.Save();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _reservationService.GetReservations().Any(e => e.ReservationId == id);
        }
    }
}

WADProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@{
    var message = TempData["AlertMessage"] ?? string.Empty;
}
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WADProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/css/sitestyle.css" rel="stylesheet" type="text/css" media="screen" runat="server" />
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="navbar-box">
                <h3 class="heading-tertiary">GoodFood</h3>
            </div>

            <ul class="navbar-list">
                <li class="navbar-item">
                    <a class="navbar-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="navbar-item">
                    <a class="navbar-link" asp-area="" asp-controller="MenuItem" asp-action="Index">Menu</a>
                </li>
                <li class="navbar-item">
                    <a class="navbar-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                </li>
                <li class="navbar-item">
                    <a class="navbar-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                </li>
                <li class="navbar-item">
                    <a class="navbar-link-book" asp-area="" asp-controller="Reservation" asp-action="Create">Book</a>
                </li>
                <li class="navbar-item">
                    <partial name ="_LoginPartial"/>
                </li>
            </ul>
            <div class="toggle">
                <div class="line1"></div>
                <div class="line2"></div>
                <div class="line3"></div>
            </div>
        </nav>
    </header>

<div>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSectionAsync("Scripts", required: false)
<script type="text/javascript">
    var message = '@message';
    if (message) {
        alert(message);
    }
</script>
</body>
</html>